CREATE TABLE `branchsol` (
    `SOL ID`	INT,
    `SOL Detail`	VARCHAR(512)
);

INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('176', 'Corporate Office, Hattisar');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('177', 'Durbarmarg');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('178', 'Newroad');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('179', 'Embassy of India');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('180', 'Birgunj');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('181', 'Rampur');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('182', 'Birtamod');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('183', 'Shishuwa');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('184', 'PPO - Pokhara');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('185', 'Biratnagar');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('186', 'PPO - Dharan');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('187', 'Bhairahawa');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('188', 'Janakpur');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('189', 'Pokhara');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('190', 'Dharan');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('191', 'Butwal');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('192', 'Teku');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('193', 'Consulate General of India, Birgunj');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('194', 'Narayangarh');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('195', 'Nepalgunj');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('196', 'PPO - Kathmandu');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('428', 'Sindhuli');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('198', 'Walling');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('199', 'Damauli');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('200', 'Hetauda');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('201', 'Gongabu');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('202', 'Patan');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('203', 'New Baneshwore');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('225', 'Corporate Credit, Hattisar');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('212', 'ITAHARI');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('208', 'surkhet');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('213', 'kalanki');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('219', 'DAMAK');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('229', 'Terathum');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('230', 'LAHAN');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('231', 'Bargachhi biratnagar');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('211', ' ilam ');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('225', 'COMMERCIAL BRANCH');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('176', 'CORPORATE OFFICE, SBI  NEPAL');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('185', 'BIRATNAGAR');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('180', 'BIRGUNJ');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('189', 'POKHARA');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('178', 'NEW ROAD');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('187', 'BHAIRAHAWA');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('195', 'NEPALGUNJ');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('182', 'BIRTAMOD');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('203', 'NEW BANESHWAR BRANCH');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('194', 'NARAYANGARH');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('191', 'BUTWAL');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('183', 'SRIJANA CHOWK BRANCH');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('188', 'JANAKPUR');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('190', 'DHARAN');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('201', 'GONGABU BRANCH');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('214', 'DALLU BRANCH');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('219', 'DAMAK BRANCH');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('222', 'DHANGADI BRANCH');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('198', 'WALING BRANCH');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('221', 'MAHENDRANAGAR BRANCH');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('213', 'KALANKI');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('215', 'KULESHWOR BRANCH');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('216', 'GWARKO BRANCH');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('220', 'TIKAPUR BRANCH');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('199', 'DAMAULI BRANCH');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('206', 'DANG');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('197', 'BAGLUNG BRANCH');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('218', 'ABU KHAIRENI BRANCH');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('181', 'RAMPUR');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('208', 'SURKHET');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('192', 'TEKU');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('223', 'SHISHUWA BRANCH');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('193', 'CONSULATE GENERAL OF INDIA, BRG');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('230', 'LAHAN');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('212', 'ITAHARI');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('217', 'GAUSHALA BRANCH');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('233', 'SINAMANGAL');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('232', 'BHAINSEPATI');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('229', 'MYANGLUNG');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('207', 'BHAKTAPUR');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('204', 'MAHARAJGUNJ BRANCH');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('196', 'BHARATIYA GORKHA');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('231', 'BARGACHHI');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('211', 'ILAM');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('228', 'SANDHIKHARKA');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('224', 'PARASI BRANCH');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('227', 'REGIONAL OFFICE-NEPALGUNJ');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('226', 'REGIONAL OFFICE-BIRATNAGAR');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('179', 'INDIAN EMBASSY, KATHMANDU');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('210', 'PALPA');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('209', 'GULMI');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('205', 'BOUDDHA');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('186', 'PPO-DHARAN');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('200', 'HETAUDA');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('202', 'PATAN BRANCH');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('184', 'PPO,POKHRA');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('177', 'DURBAR MARG');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('237', 'Thamel');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('204', 'Maharajgunj');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('205', 'BOUDDHA');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('206', 'DANG');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('207', 'BHAKTAPUR');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('208', 'surkhet');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('209', 'GULMI');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('210', 'PALPA');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('211', ' ILAM ');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('212', 'ITAHARI');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('213', 'kalanki');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('214', 'DALLU BRANCH');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('215', 'KULESHWOR BRANCH');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('216', 'GWARKO BRANCH');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('217', 'GAUSHALA BRANCH');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('218', 'ABU KHAIRENI BRANCH');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('219', 'DAMAK BRANCH');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('220', 'TIKAPUR BRANCH');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('221', 'MAHENDRANAGAR BRANCH');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('222', 'DHANGADI BRANCH');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('223', 'SHISHUWA BRANCH');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('224', 'PARASI BRANCH');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('225', 'COMMERCIAL BRANCH');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('226', 'REGIONAL OFFICE-BIRATNAGAR');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('227', 'REGIONAL OFFICE-NEPALGUNJ');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('228', 'SANDHIKHARKA');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('229', 'MYANGLUNG');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('230', 'LAHAN');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('231', 'BARGACHHI');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('232', 'BHAINSEPATI');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('233', 'SINAMANGAL');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('234', 'BESISAHAR BRANCH');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('235', 'RATNANAGAR BRANCH');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('236', 'PHIDIM BRANCH');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('237', 'THAMEL BRANCH');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('238', 'BARDIBAS');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('239', 'CHANDRANIGAHAPUR');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('245', 'HAKIM CHOK');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('249', 'CHANDRAUTA ');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('253', 'Simara');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('248', 'Battar');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('251', 'Mirchaiya');
INSERT INTO `branchsol` (`SOL ID`, `SOL Detail`) VALUES ('252', 'Rajbiraj');
